/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Service.StudentService;
import dao.AdminDAO;
import java.awt.Color;
import java.awt.Cursor;
import model.User;
import util.DBConnection;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import model.Admin;
import model.Student;
/**
 *
 * @author jesse
 */
public class EditstudentFrame extends javax.swing.JFrame {
    private User currentUser;
    private StudentService studentService;
    private AdminDAO adminDAO= new AdminDAO();
    private int studentId;
    private int adminId;
    private Student Original;

    /**
     * Creates new form EditstudentFrame
     */
    public EditstudentFrame(User currentUser, int studentId) {
        initComponents();
        this.currentUser= currentUser;
        this.studentId= studentId; 
        this.studentService= new StudentService();
        saveButton.setEnabled(false);
        loadDataAsync();
        
    }
    private void loadDataAsync(){
        Cursor oldCursor= getCursor();
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        SwingWorker<StudentData, Void> worker= new SwingWorker<>(){
            @Override
            protected StudentData doInBackground() throws Exception{
                Admin admin= adminDAO.getAdminByUserId(currentUser.getId());
                if(admin== null){
                    throw new Exception("Admin not found");
                }
                int adminId= admin.getAdminId();
                try(Connection conn= DBConnection.getConnection()){
                    Student student= studentService.getStudentById(studentId, adminId, conn);
                    if(student== null){
                        throw new Exception("Student not found");
                    }
                    return new StudentData(adminId, student);
                }
            }
            @Override
            protected void done(){
                try{
                    StudentData data= get();
                    EditstudentFrame.this.adminId= data.adminId;
                    EditstudentFrame.this.Original= data.student;
                    //populate ui
                    firstnameField.setText(data.student.getFirstName());
                    lastnameField.setText(data.student.getLastName());
                    Box.setSelectedItem(data.student.getGender());
                    deptField.setText(data.student.getDepartment());
                    DOBField.setText(data.student.getDOB().toString());
                    String status= data.student.getStatus();
                    labelStatus.setText("Status: "+ (status !=null ? status : "Unknown"));
                    //colors
                    switch(status !=null ? status.toLowerCase() : ""){
                        case "active" -> labelStatus.setForeground(Color.green);
                        case "inactive" -> labelStatus.setForeground(Color.ORANGE);
                        case "graduated" -> labelStatus.setForeground(Color.blue);
                        case "archived" -> labelStatus.setForeground(Color.gray);
                        default -> labelStatus.setForeground(Color.black);
                    }
                    saveButton.setEnabled(true);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(EditstudentFrame.this,
                        "Error loading student: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);

                new ManageStudentFrame(currentUser).setVisible(true);
                EditstudentFrame.this.dispose();
                }finally{
                    setCursor(oldCursor);
                }
            }
        };
        worker.execute();
    }
    private static class StudentData{
        final int adminId;
        final Student student;
        
        StudentData(int adminId, Student student){
            this.adminId= adminId;
            this.student= student;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deptField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DOBField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Box = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        firstnameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        deptField.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N
        deptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N
        jLabel5.setText("Department");

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N
        jLabel6.setText("DOB");

        Box.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N
        Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENDER", "MALE", "FEMALE" }));

        cancelButton.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        firstnameField.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N

        saveButton.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N
        jLabel2.setText("Firstname");

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N
        jLabel3.setText("Lastname");

        lastnameField.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        jLabel1.setText("  EDIT STUDENTS");

        labelStatus.setFont(new java.awt.Font("Footlight MT Light", 0, 13)); // NOI18N
        labelStatus.setText("jLabel8");

        jButton1.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(firstnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(lastnameField)
                                        .addComponent(deptField)
                                        .addComponent(DOBField))
                                    .addComponent(Box, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Box, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if(Original !=null){
            firstnameField.setText(Original.getFirstName());
            lastnameField.setText(Original.getLastName());
            Box.setSelectedItem(Original.getGender());
            deptField.setText(Original.getDepartment());
            DOBField.setText(Original.getDOB().toString());
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
        String firstname= firstnameField.getText().trim();
        String lastname= lastnameField.getText().trim();
        String gender= (String) Box.getSelectedItem();
        String department= deptField.getText().trim();
        //Validation
        if(firstname.isEmpty() || lastname.isEmpty() || department.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill all fields", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if("GENDER".equals(gender)){
           JOptionPane.showMessageDialog(this, "Please select a gender", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        LocalDate dob;
        try{
            dob= LocalDate.parse(DOBField.getText().trim());
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(this, "Invalid date format. Use yyyy-MM-dd", "Date Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Student student= new Student();
        student.setStudentId(studentId);
        student.setAdminId(this.adminId);
        student.setFirstName(firstname);
        student.setLastName(lastname);
        student.setGender(gender);
        student.setDepartment(department);
        student.setDOB(dob);
        student.setEnrollmentDate(Original.getEnrollmentDate());
        student.setUpdatedAt(LocalDateTime.now());
        
        boolean updated= studentService.updateStudent(student);
        if(updated){
            JOptionPane.showMessageDialog(this, "Student updated successfully");
            new ManageStudentFrame(currentUser).setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Failed to update student", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
            e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ManageStudentFrame(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditstudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditstudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditstudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditstudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditstudentFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box;
    private javax.swing.JFormattedTextField DOBField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField deptField;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
