/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Service.ArchiveSchedulerService;
import Service.AuthService;
import Service.GradeService;
import Service.TranscriptArchiveService;
import dao.AdminDAO;
import dao.EnrollmentDAO;
import dao.GradeDAO;
import dao.StudentDAO;
import dao.TranscriptArchivedDAO;
import dao.UserDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.User;
import javax.swing.*;
import java.sql.Connection;
import java.util.Arrays;
import model.Student;
import util.DBConnection;

/**
 *
 * @author jesse
 */
public class loginFrame extends javax.swing.JFrame {
   

    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ForgotpasswordButton = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel1.setText("Student System- Login");

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel3.setText("Password");

        LoginButton.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        RegisterButton.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        PasswordField.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        usernameField.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel5.setText("Status:");

        ForgotpasswordButton.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        ForgotpasswordButton.setText("forgot password?");
        ForgotpasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotpasswordButtonActionPerformed(evt);
            }
        });

        labelStatus.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordField)
                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(ForgotpasswordButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(ForgotpasswordButton)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        //register button
        new RegisterFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String username= usernameField.getText().trim();
        char[] passwordChars= PasswordField.getPassword();
        String password= new String(passwordChars).trim();
        //clear char array from memory
        Arrays.fill(passwordChars, '\0');
        if(username.isEmpty() || password.isEmpty()){
            labelStatus.setText("please enter username and password");
            labelStatus.setForeground(Color.orange);
            return;
        }
        AuthService authService= new AuthService();
        User user= authService.login(username, password);
        
        if(user== null){
            labelStatus.setText("Invalid username, password or account isn't accessible");
            labelStatus.setForeground(Color.red);
            return;
        }
        //check default password
        if(user.getIsDefaultPassword() || user.getFirstLogin()){
            labelStatus.setText("You are using default password. please change it now");
            labelStatus.setForeground(Color.orange);
            
            ChangePasswordFrame cpf= new ChangePasswordFrame(user, true, null);
            cpf.setVisible(true);
            this.dispose();//close frame
            return;
        }
        //check role
        if("admin".equalsIgnoreCase(user.getRole())){
            labelStatus.setText("Login successful! Initializing..");
            labelStatus.setForeground(Color.green);
            //show loading dialog
            JDialog loading= new JDialog(this, "Processing", true);
            JLabel loadinglabel= new JLabel("Running auto-archive check... Pls wait.");
            loadinglabel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
            loading.add(loadinglabel);
            loading.pack();
            loading.setLocationRelativeTo(this);
            loading.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
            //run the auto-archive scheduler in background
            SwingWorker<Void, Void> archiveWorker= new SwingWorker<>(){
                @Override
                protected Void doInBackground() throws Exception{
            
                TranscriptArchivedDAO transcriptDAO= new TranscriptArchivedDAO();
                StudentDAO studentDAO= new StudentDAO();
                EnrollmentDAO enrollmentDAO= new EnrollmentDAO();
                AdminDAO adminDAO= new AdminDAO();
                GradeService gradeService= new GradeService();
                TranscriptArchiveService transcriptArchiveService= new TranscriptArchiveService(transcriptDAO, gradeService, studentDAO, 
                enrollmentDAO, adminDAO);
                ArchiveSchedulerService scheduler= new ArchiveSchedulerService(transcriptArchiveService);
                scheduler.checkAutoArchive();
                return null;
            }
                @Override
                protected void done() {
                    loading.dispose();
                    try{
                        get();
            AdminDashboardFrame adf= new AdminDashboardFrame(user);
            adf.setVisible(true);
            loginFrame.this.dispose();
                    }catch(Exception e){
                        e.printStackTrace();
                        System.err.println("Äuto-archiving failed: "+ e.getMessage());
                        
                        int choice= JOptionPane.showConfirmDialog(loginFrame.this,"Auto-archive check failed. Continue to dashboard anyway?","Archive Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                        if(choice== JOptionPane.YES_OPTION){
                            AdminDashboardFrame adf= new AdminDashboardFrame(user);
                            adf.setVisible(true);
                            loginFrame.this.dispose();
                        }else{
                            labelStatus.setText("Login cancelled");
                            labelStatus.setForeground(Color.red);
                        }
                    }
                }
            };
            archiveWorker.execute();
            loading.setVisible(true);
        }else if("student".equalsIgnoreCase(user.getRole())){
            StudentDAO studentDAO= new StudentDAO();
            Student student= studentDAO.getStudentByUserId(user.getId());
            if(student== null){
                labelStatus.setText("Student record not found. contact your admin");
                labelStatus.setForeground(Color.red);
                return;
            }
            String status= student.getStatus();
            if(status== null) status= "active";
            switch(status.toLowerCase()){
                case "inactive":
                    labelStatus.setText("Your account is currently inactive. Contact your admin");
                    labelStatus.setForeground(Color.red);
                    return;
                case "archived":
                    labelStatus.setText("Your account has been archived. you no longer have access");
                    labelStatus.setForeground(Color.orange);
                    return;
                case "graduated":
                    labelStatus.setText("Welcome, graduate! View only access granted");
                    labelStatus.setForeground(Color.green);
                    
                    GradStudentDashboardFrame grad= new GradStudentDashboardFrame(user);
                    grad.setGraduatedMode(true);
                    grad.setVisible(true);
                    this.dispose();
                    return;
                case "active":
                default:
                    labelStatus.setText("Login successful! Redirecting..");
                    labelStatus.setForeground(Color.green);
                    
                    StudentDashboardFrame sdf= new StudentDashboardFrame(student);
                    sdf.setVisible(true);
                    this.dispose();
                    return;
            }
            
        }
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void ForgotpasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotpasswordButtonActionPerformed
        // TODO add your handling code here:
        new ForgotPasswordFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ForgotpasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ForgotpasswordButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
