/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Service.AdminService;
import Service.StudentService;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import model.Admin;
import java.sql.SQLException;
import model.Student;
import model.User;
import java.sql.Connection;
import java.util.Arrays;
import javax.swing.SwingWorker;
import util.DBConnection;

/**
 *
 * @author jesse
 */
public class RegisterFrame extends javax.swing.JFrame {
  
    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        setLocationRelativeTo(null);
        initCustomSettings();
        initListeners();
        
        ButtonGroup roleGroup= new ButtonGroup();
        roleGroup.add(AdminRadio);
        roleGroup.add(StudentRadio);
    }
    // custom settings
     private void initCustomSettings(){
        deptField.setEnabled(false);
        DobField.setEnabled(false);
        enrollField.setEnabled(false);
        AdminPinField.setEnabled(false);
        Genderbox.setEnabled(false);
        labelStatus.setText("Pls select a role: Admin or Student");
        labelStatus.setForeground(Color.blue);
    }
    // add listerners
    private void initListeners(){
        AdminRadio.addActionListener(e -> updateFieldsForRole());
        StudentRadio.addActionListener(e -> updateFieldsForRole());
        RegisterButton.addActionListener(this::RegisterButtonActionPerformed);
    }
    //update fields based on role selection
    private void updateFieldsForRole(){
        boolean isAdmin= AdminRadio.isSelected();
        boolean isStudent= StudentRadio.isSelected();
        deptField.setEnabled(isStudent);
        DobField.setEnabled(isStudent);
        enrollField.setEnabled(isStudent);
        AdminPinField.setEnabled(isStudent);
        Genderbox.setEnabled(isStudent);
        if(isAdmin){
            deptField.setText("");
            DobField.setText("");
            enrollField.setText("");
            AdminPinField.setText("");
            Genderbox.setSelectedItem("Gender");
            labelStatus.setText("Fill in required fields for Admin");
        }else if(isStudent){
            labelStatus.setText("Fill in required fields for Student");
        }else{
            labelStatus.setText("Pls select a role: Admin or student");
        }
        labelStatus.setForeground(Color.orange);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        PasswordField1 = new javax.swing.JPasswordField();
        PasswordField2 = new javax.swing.JPasswordField();
        BackButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        firstnameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AdminRadio = new javax.swing.JRadioButton();
        StudentRadio = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AdminPinField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        deptField = new javax.swing.JTextField();
        enrollField = new javax.swing.JFormattedTextField();
        DobField = new javax.swing.JFormattedTextField();
        Genderbox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jLabel1.setText("STUDENT SYSTEM- REGISTER");

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel2.setText("FIRST NAME");

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel3.setText("USERNAME");

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel4.setText("PASSWORD");

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel5.setText("CONFIRM");

        RegisterButton.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        RegisterButton.setText("REGISTER ACCOUNT");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        usernameField.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N

        PasswordField1.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        PasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField1ActionPerformed(evt);
            }
        });

        PasswordField2.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        PasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField2ActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel6.setText("LAST NAME");

        lastnameField.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });

        firstnameField.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        firstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel7.setText("ROLE:");

        AdminRadio.setFont(new java.awt.Font("Footlight MT Light", 0, 10)); // NOI18N
        AdminRadio.setText("ADMIN");
        AdminRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminRadioActionPerformed(evt);
            }
        });

        StudentRadio.setFont(new java.awt.Font("Footlight MT Light", 0, 10)); // NOI18N
        StudentRadio.setText("STUDENT");
        StudentRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentRadioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel8.setText("DEPARTMENT");

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel9.setText("ENROLLMENT DATE");

        jLabel10.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel10.setText("GENDER");

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel11.setText("Admin PIN:");

        AdminPinField.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel12.setText("DOB");

        deptField.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        deptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptFieldActionPerformed(evt);
            }
        });

        Genderbox.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        Genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENDER", "MALE", "FEMALE" }));

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel13.setText("Status:");

        labelStatus.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(AdminRadio)
                        .addGap(111, 111, 111)
                        .addComponent(StudentRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(321, 321, 321))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordField2)
                                    .addComponent(firstnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(BackButton)))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastnameField)
                                    .addComponent(deptField)
                                    .addComponent(enrollField, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(DobField)
                                    .addComponent(Genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AdminPinField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AdminRadio)
                    .addComponent(StudentRadio))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminPinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField1ActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
       try{
           //determine role
           boolean isAdmin= AdminRadio.isSelected();
           boolean isStudent= StudentRadio.isSelected();
           if(!isAdmin && !isStudent){
               labelStatus.setText("Pls selest a role: Admin or Student");
               labelStatus.setForeground(Color.orange);
               return;
           }
           //common fields
           String firstName= firstnameField.getText().trim();
           String lastName= lastnameField.getText().trim();
           String username= usernameField.getText().trim();
           
           //role-specific fields
           String department= deptField.getText().trim();//for student
           String Dob= DobField.getText().trim();
           String enrollment= enrollField.getText().trim();
           String adminPin= AdminPinField.getText().trim();
           String gender= Genderbox.getSelectedItem().toString();
           //get password as char
           char[] passwordChars= PasswordField1.getPassword();
           char[] confirmChars= PasswordField2.getPassword();
           //convert to string for processing
           String password= new String(passwordChars).trim();
           String confirm= new String(confirmChars).trim();
           //clear the char arrays from memory 
           Arrays.fill(passwordChars, '\0');
           Arrays.fill(confirmChars, '\0');
           //validation
           if(firstName.isEmpty() || lastName.isEmpty() || username.isEmpty() || password.isEmpty() || confirm.isEmpty()){
               labelStatus.setText("Pls fill in all required fields.");
               labelStatus.setForeground(Color.red);
               return;
           }
           if(!password.equals(confirm)){
               labelStatus.setText("Passwords do not match.");
               labelStatus.setForeground(Color.red);
               return;
           }
           if(password.length() <6 || password.length() >16){
               labelStatus.setText("Password must be 6-16 characters");
               labelStatus.setForeground(Color.orange);
               return;
           
           }
           //disable button to prevent double clicks
           RegisterButton.setEnabled(false);
           labelStatus.setText("Registering...");
           labelStatus.setForeground(Color.blue);
           //role specific
           if(isStudent){
               if(department.isEmpty() || Dob.isEmpty() || enrollment.isEmpty()){
                   labelStatus.setText("Pls fill in all Fields");
                   labelStatus.setForeground(Color.red);
                   RegisterButton.setEnabled(true);
                   return;
               }
               if(adminPin.isEmpty()){
                   labelStatus.setText("Admin Pin is required for student registration");
                   labelStatus.setForeground(Color.red);
                   RegisterButton.setEnabled(true);
                   return;
               }
               if(gender.equalsIgnoreCase("Gender")){
               labelStatus.setText("Pls select a gender");
               labelStatus.setForeground(Color.orange);
               RegisterButton.setEnabled(true);
               return;
               }
               LocalDate dob, enrollmentDate;
               try{
                   dob= LocalDate.parse(Dob, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                   enrollmentDate= LocalDate.parse(enrollment, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                   //validate dob
                   if(dob.isAfter(LocalDate.now())){
                       labelStatus.setText("Date of birth cannot be in the future");
                       labelStatus.setForeground(Color.red);
                       RegisterButton.setEnabled(true);
                       return;
                   }
                   if(dob.isBefore(LocalDate.now().minusYears(70))){
                       labelStatus.setText("Invalid date of birth(too old)");
                       labelStatus.setForeground(Color.red);
                       RegisterButton.setEnabled(true);
                       return;
                   }
                   //validate enrollment
                   if(enrollmentDate.isAfter(LocalDate.now())){
                       labelStatus.setText("Enrollment date cannot be in the future");
                       labelStatus.setForeground(Color.red);
                       RegisterButton.setEnabled(true);
                       return;
                   }
                   if(enrollmentDate.isBefore(dob)){
                       labelStatus.setText("Enrollment cannot be before date of birth");
                       labelStatus.setForeground(Color.red);
                       RegisterButton.setEnabled(true);
                       return;
                   }

               }catch(DateTimeParseException e){
                 labelStatus.setText("Invalid date format. use yyyy-mm-dd.");
                 labelStatus.setForeground(Color.orange);
                 RegisterButton.setEnabled(true);
                 return;
               }
                LocalDateTime now= LocalDateTime.now();
                
               //construct user & student objects
               User user= new User();
               user.setUsername(username);
               user.setFirstName(firstName);
               user.setPassword(password);
               user.setLastName(lastName);
               user.setRole("student");
              
               Student student= new Student();
               student.setDepartment(department);
               student.setDOB(dob);
               student.setGender(gender);
               student.setFirstName(firstName);
               student.setLastName(lastName);
               student.setEnrollmentDate(enrollmentDate);
               student.setUpdatedAt(now);
               student.setCreatedAt(now);
               
               //Run the registration in background
               SwingWorker<Boolean, Void> worker= new SwingWorker<>(){
                   @Override
                   protected Boolean doInBackground() throws Exception{
                       StudentService studentService= new StudentService();
                       return studentService.registerStudentWithPIn(user, adminPin, student);
                   }
                   @Override
                   protected void done(){
                       try{
                           boolean success= get();
                           if(!success){
                   labelStatus.setText("Registration failed: invalid Admin Pin or username exists");
                   labelStatus.setForeground(Color.red);
                   RegisterButton.setEnabled(true);
                   return;
               }
               labelStatus.setText("Student account created successfully!");
               labelStatus.setForeground(Color.green);
               //redirect after delay
               javax.swing.Timer timer= new javax.swing.Timer(1200, e-> {
                   new loginFrame().setVisible(true);
                   RegisterFrame.this.dispose();
               });
               timer.setRepeats(false);
               timer.start();
                       }catch(Exception e){
                           labelStatus.setText("Error: "+ e.getMessage());
                           labelStatus.setForeground(Color.red);
                           RegisterButton.setEnabled(true);
                           e.printStackTrace();
                       }
                   }
               };
               worker.execute();
               
           }else if(isAdmin){
               //constructor user & admin
               User user= new User();
               user.setFirstName(firstName);
               user.setUsername(username);
               user.setLastName(lastName);
               user.setPassword(password);
               user.setRole("admin");
               
               Admin admin= new Admin();
               //register
               SwingWorker<Boolean, Void> worker= new SwingWorker<>(){
                   @Override
                   protected Boolean doInBackground() throws Exception{
                       AdminService adminService= new AdminService();
                           return adminService.registerAdmin(user, admin);
                   }
                   @Override
                   protected void done(){
                       try{
                           boolean success= get();
                           if(!success){
                   labelStatus.setText("Registration failed: username exists.");
                   labelStatus.setForeground(Color.red);
                   RegisterButton.setEnabled(true);
                   return;
               }
               labelStatus.setText("Admin account created successfully!");
               labelStatus.setForeground(Color.green);
               //redirect after delay
               javax.swing.Timer timer= new javax.swing.Timer(1200, e-> {
                   new loginFrame().setVisible(true);
                   RegisterFrame.this.dispose();
               });
               timer.setRepeats(false);
               timer.start();
                       }catch(Exception e){
                           labelStatus.setText("Error: "+ e.getMessage());
                           labelStatus.setForeground(Color.red);
                           RegisterButton.setEnabled(true);
                           e.printStackTrace();
                       }
                   }
               };
               worker.execute();
           }
       }catch(Exception e){
           labelStatus.setText("Error"+ e.getMessage());
           labelStatus.setForeground(Color.red);
           RegisterButton.setEnabled(true);
           e.printStackTrace();
       }   
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void PasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField2ActionPerformed

    private void firstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldActionPerformed

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed

    private void deptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptFieldActionPerformed

    private void AdminRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminRadioActionPerformed

    private void StudentRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentRadioActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new loginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminPinField;
    private javax.swing.JRadioButton AdminRadio;
    private javax.swing.JButton BackButton;
    private javax.swing.JFormattedTextField DobField;
    private javax.swing.JComboBox<String> Genderbox;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JPasswordField PasswordField2;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JRadioButton StudentRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField deptField;
    private javax.swing.JFormattedTextField enrollField;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

    
    
}
