/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import model.Student;
import model.User;

/**
 *
 * @author jesse
 */
public class SettingsFrame extends javax.swing.JFrame {
    private User currentUser;
    private Student currentStudent;

    /**
     * Creates new form SettingsFrame
     */
    public SettingsFrame(User currentUser) {
        initComponents();
        this.currentUser= currentUser;
        LogLabel();
    }
    public SettingsFrame(User currentUser, Student student){
        this.currentUser= currentUser;
        this.currentStudent= student;
    }
    private void LogLabel(){
        if(currentUser != null){
            String role= currentUser.getRole() != null ? currentUser.getRole() : "User";
            loglabel.setText("Logged in as:"+ currentUser.getFirstName() + currentUser.getLastName()+ " ("+ role+ ")");
            loglabel.setForeground(Color.blue);
        }else{
            loglabel.setText("Not logged in");
            loglabel.setForeground(Color.red);
        }
    }
    //status message
    private void showMessage(String message, boolean isError){
        labelStatus.setText(message);
        labelStatus.setForeground(isError ? Color.red : Color.green);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loglabel = new javax.swing.JLabel();
        Usernamebtn = new javax.swing.JButton();
        passwordbtn = new javax.swing.JButton();
        credentialsbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel1.setText("SETTINGS");

        loglabel.setFont(new java.awt.Font("Footlight MT Light", 1, 13)); // NOI18N

        Usernamebtn.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        Usernamebtn.setText("Change Username");
        Usernamebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamebtnActionPerformed(evt);
            }
        });

        passwordbtn.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        passwordbtn.setText("Change Password");
        passwordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordbtnActionPerformed(evt);
            }
        });

        credentialsbtn.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        credentialsbtn.setText("Change Credentials");
        credentialsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credentialsbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        jLabel3.setText("Status:");

        labelStatus.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 10)); // NOI18N
        jLabel5.setText("(c)   2025 Student manager System");

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 0, 12)); // NOI18N
        jLabel6.setText("(PIN & Profile Info)");

        backbtn.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(credentialsbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Usernamebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Usernamebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(passwordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credentialsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if("admin".equalsIgnoreCase(currentUser.getRole())){
            new AdminDashboardFrame(currentUser).setVisible(true);
        }else if("student".equalsIgnoreCase(currentUser.getRole())){
            if(currentStudent != null && "graduated".equalsIgnoreCase(currentStudent.getStatus())){
               GradStudentDashboardFrame gradFrame= new GradStudentDashboardFrame(currentUser);
               gradFrame.setGraduatedMode(true);
               gradFrame.setVisible(true);
            }else{
            new StudentDashboardFrame(currentStudent).setVisible(true);
            }
        }else{
            showMessage("Unknown user role", true);
        }
    }//GEN-LAST:event_backbtnActionPerformed

    private void passwordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordbtnActionPerformed
        // TODO add your handling code here:
        try{
        ChangePasswordFrame cpf= new ChangePasswordFrame(currentUser, false, this);
        cpf.setVisible(true);
        this.setVisible(false);
        }catch(Exception e){
            showMessage("Error opening change password:"+ e.getMessage(), true);
        }
    }//GEN-LAST:event_passwordbtnActionPerformed

    private void UsernamebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamebtnActionPerformed
        // TODO add your handling code here:
        try{
        ChangeUsernameFrame cuf= new ChangeUsernameFrame(currentUser, this);
        cuf.setVisible(true);
        this.setVisible(false);
        }catch(Exception e){
            showMessage("Error opening change password:"+ e.getMessage(), true);
        }
    }//GEN-LAST:event_UsernamebtnActionPerformed

    private void credentialsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credentialsbtnActionPerformed
        // TODO add your handling code here:
        try{
        ChangeCredentialsFrame ccf= new ChangeCredentialsFrame(currentUser, this);
        ccf.setVisible(true);
        this.setVisible(false);
        }catch(Exception e){
            showMessage("Error opening change password:"+ e.getMessage(), true);
        }
    }//GEN-LAST:event_credentialsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsFrame().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Usernamebtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton credentialsbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel loglabel;
    private javax.swing.JButton passwordbtn;
    // End of variables declaration//GEN-END:variables
}
